// ✅ This runs when quiz.html loads and displays questions
document.addEventListener("DOMContentLoaded", () => {
  const form = document.getElementById("quizForm");
  if (!form) return;

  const questions = JSON.parse(localStorage.getItem("questions")) || [];

  if (!questions.length) {
    const quizBox = document.getElementById("quizContainer");
    quizBox.innerHTML = "<p>⚠️ No questions found. Please go back and start again.</p>";
    return;
  }

  questions.forEach((q, index) => {
    const div = document.createElement("div");
    div.className = "question-box question-inner";
    div.innerHTML = `<h3>Q${index + 1}: ${q.question}</h3>` +
      q.options.map(opt =>
        `<label><input type="radio" name="q${index}" value="${opt}"> ${opt}</label><br>`
      ).join("");
    form.appendChild(div);
  });
});

// ✅ This runs when student clicks "Start Quiz" (on student.html)
async function startQuiz() {
  const name = document.getElementById("name")?.value.trim();
  const email = document.getElementById("email")?.value.trim();
  const topic = document.getElementById("topic")?.value.trim();
  const difficulty = document.getElementById("difficulty")?.value;
  const num = parseInt(document.getElementById("numQuestions")?.value || "10");

  if (!name || !email || !topic || !difficulty || !num) {
    alert("Please fill out all fields.");
    return;
  }

  const btn = document.getElementById("startBtn");
  if (btn) {
    btn.disabled = true;
    btn.textContent = "Generating...";
  }

  try {
    const res = await fetch("http://127.0.0.1:8000/generate_quiz", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        name,
        email,
        topic,
        difficulty,
        num_questions: num
      })
    });

    if (!res.ok) {
      alert("Quiz generation failed.");
      if (btn) {
        btn.disabled = false;
        btn.textContent = "Start Quiz";
      }
      return;
    }

    const data = await res.json();

    if (!data.questions || !data.questions.length) {
      alert("Quiz generation returned no questions. Try again.");
      if (btn) {
        btn.disabled = false;
        btn.textContent = "Start Quiz";
      }
      return;
    }

    localStorage.setItem("questions", JSON.stringify(data.questions));
    localStorage.setItem("student_name", name);
    localStorage.setItem("user_email", email);
    window.location.href = "quiz.html";

  } catch (err) {
    alert("Failed to generate quiz.");
    console.error(err);
    if (btn) {
      btn.disabled = false;
      btn.textContent = "Start Quiz";
    }
  }
}

// ✅ This is triggered when the quiz is submitted (on quiz.html)
function submitQuiz() {
  const questions = JSON.parse(localStorage.getItem("questions")) || [];
  const name = localStorage.getItem("student_name");
  const email = localStorage.getItem("user_email");

  let score = 0;
  const answers = [];

  questions.forEach((q, i) => {
    const selected = document.querySelector(`input[name="q${i}"]:checked`);
    const selectedAns = selected ? selected.value : "Not answered";
    const isCorrect = selectedAns === q.answer;
    if (isCorrect) score++;

    answers.push({
      question: q.question,
      selected: selectedAns,
      correct: q.answer,
      explanation: q.explanation || "This answer is generated by the model."
    });
  });

  const resultBox = document.getElementById("resultBox");
  resultBox.style.display = "block";
  resultBox.innerHTML = `<p><strong>🎯 You scored ${score} out of ${questions.length}</strong></p><hr>`;

  answers.forEach((ans, i) => {
    const wrong = ans.selected !== ans.correct;
    resultBox.innerHTML += `
      <p><strong>Q${i + 1}:</strong> ${ans.question}</p>
      <p>Your answer: ${ans.selected}</p>
      <p class="${wrong ? 'correct-answer' : ''}">Correct answer: ${ans.correct}</p>
      <p class="feedback">Explanation: ${ans.explanation}</p>
      <hr />
    `;
  });

  fetch("http://127.0.0.1:8000/submit_quiz", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name,
      email,
      topic: questions[0]?.topic || "N/A",
      difficulty: questions[0]?.difficulty || "N/A",
      score,
      questions: answers
    })
  });
}

// ✅ Attach startQuiz to Start Quiz button
document.addEventListener("DOMContentLoaded", () => {
  const btn = document.getElementById("startBtn");
  if (btn) {
    btn.addEventListener("click", startQuiz);
  }
});